[build]
  command = "npm install --prefix netlify/functions && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "node ./node_modules/vite/bin/vite.js --port 5173"
  targetPort = 5173
  port = 8888
  host = "127.0.0.1"
  publish = "dist"
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
